spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.74.128:9300
  rabbitmq:
    host: 192.168.74.128
    virtual-host: /leyou
    username: leyou
    password: leyou
  #为了test新增
  #profiles:
    #active: dev

  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null


server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15