spring:
  application:
    name: cart-service
  redis:
    host: 127.0.0.1

server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: D:\JAVAwork\rsa\\rsa.pub # ¹«Ô¿µØÖ·
    cookieName: LY_TOKEN